[package]
name = "atom_os"
version = "0.1.0"
edition = "2021"
authors = ["LukasDoesDev <lukasdoesdev@gmail.com>"]

[dependencies]
# TODO: Upgrade bootloader and volatile
bootloader = "0.9.8"
volatile = "0.3.0"
spin = "0.9.2"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
