[target.'cfg(target_os = "none")']
runner = "cargo run --package atom_os_boot --"

[alias]
kbuild = "build --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --hide-qemu --timeout"
kclippy = "clippy --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kcheck = "check --target x86_64-atom_os.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
